### PR TITLE
Add simulative tests for wrangler/move thread functionality 

### PR DESCRIPTION
**Pull request by nickmisasi**
#### Summary
First time!

This PR adds a simulative load test for https://github.com/mattermost/mattermost-server/pull/21122. I believe I've got things in the proper place - it runs locally and I can see threads being moved by the simulator. I've not tried this with Terraform yet - wanted to open a draft and ensure I'm on the right track before I head down that path. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-49665

### CODE REVIEW

**Comment by agarciamontoro** [comment]
Hey, @nickmisasi, do you want me to take a deeper look or what we discussed in the DM is enough? Let me know how I can help!

**Comment by nickmisasi** [comment]
@agarciamontoro I think I'm on the right track and what we've discussed should get me the rest of the way. Haven't had the time to look back at this - I can close the PR for now if you want to clear up the backlog?

**Comment by agarciamontoro** [comment]
@nickmisasi Up to you whether closing this one or keep working on it. I don't have any problem with it being on the draft state here. I'll just ask you from time to time to not let it die :)

**Pull request closed without merging**
