### PR TITLE
[MM-26168] websocket/client: change log level for close error

### PR DESCRIPTION
**Pull request by isacikgoz**
#### Summary
This PR changes the log level for an expected scenario for websocket client.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-26168

### CODE REVIEW

**Comment by agnivade** [comment]
Can you explain what is happening here? I set the debug level to warn to explicitly mean that it is _not_ an error. But it can also happen if the server closes connection, so I think it's not completely right to mark it debug.

From what I saw, it looked like we are calling Close ourselves. If that's somehow intentional, then perhaps we can add a debug line on the Close call which will further clarify that this connection close is intentional because we are closing it ourselves.

**Comment by isacikgoz** [comment]
> Can you explain what is happening here? I set the debug level to warn to explicitly mean that it is _not_ an error. But it can also happen if the server closes connection, so I think it's not completely right to mark it debug.

I expect a warning level log is something should be taken care of. The majority of having this error caused by our side. Therefore, I thought this is an expected error/warning.

> From what I saw, it looked like we are calling Close ourselves. If that's somehow intentional, then perhaps we can add a debug line on the Close call which will further clarify that this connection close is intentional because we are closing it ourselves.

Yes, the close seems to be intentional. Wouldn't adding another debug line when `Close()` increase the verbosity? I mean does having this warning on every disconnect carry valuable information at warning level? Would like to hear @streamer45 as well.

**Comment by agnivade** [comment]
Ah I see that it is coming from the reload action. That's where I guess mine and @streamer45's confusion came from.

We actually missed the log line that the page was reloaded. I think I am fine with things as-is. There may not be a need to change anything.

But 0/5 on whatever you guys think.

**Comment by streamer45** [comment]
Yes, so my question would be whether it's possible, without going down the old road of races and bugs, to first shutdown the ws reader goroutine and then close the connection.  
I believe that would avoid this warning and will result in a cleaner way of closing the connection.

**Comment by agnivade** [comment]
Not really. Closing the connection is the way to break from the reader. This keeps it dead-simple and race-free.

**Pull request merged**
