### PR TITLE
Do not merge: Use sysadmin client when needed

### PR DESCRIPTION
**Pull request by agarciamontoro**
#### Summary
This PR isolates the controversial sysadmin changes, so we can use them in the testing branch for the current efforts without merging them to master.

No need to do a proper review, the goal of this PR is purely to increase visibility of this decision.

#### Ticket Link
--

### CODE REVIEW

**Review by streamer45 — APPROVED** [review]

**Comment by agnivade** [comment]
"controversial" :P

**Comment by agnivade** [comment]
@agarciamontoro @streamer45 - What do we want to do with this one? Do we want to follow some other approach or merge this? I am happy to just pause on this till we finish the ceiling tests and then come back to this and spend some time to find a better approach. LMK.

**Comment by agarciamontoro** [comment]
I'm ok pausing on this and getting back to it once the ceiling tests are done (or at least underway).

**Comment by streamer45** [comment]
I still think there are less hacky ways to achieve the same result. (see https://github.com/mattermost/mattermost-load-test-ng/pull/608#discussion_r1228505681).

**Comment by agarciamontoro** [comment]
@agnivade, I'm proposing that we close this PR and track it with a new ticket. Would you be willing to open one? I feel you have more context on the issue and potential solutions than I do at the moment.

**Comment by agnivade** [comment]
Done: https://mattermost.atlassian.net/browse/MM-53696

**Pull request closed without merging**
