### PR TITLE
[MM-23507] Fix panic on some error cases

### PR DESCRIPTION
**Pull request by streamer45**
#### Summary

PR fixes a panic caused by not handling the correct error.

#### Ticket

https://mattermost.atlassian.net/browse/MM-23507

### CODE REVIEW

**Comment by streamer45** [comment]
The panic was actually happening here:

https://github.com/mattermost/mattermost-load-test-ng/blob/f3867eab264b15545ed212f4b694415a5d98c513/loadtest/control/error.go#L14-L16

Adding a check for `e.Err == nil` would have avoided this but probably would not have spotted the generating issue so quickly. Should we add a check or rely on *correct usage* like we did so far?

**Comment by isacikgoz** [comment]
> Adding a check for `e.Err == nil` would have avoided this but probably would not have spotted the generating issue so quickly. Should we add a check or rely on _correct usage_ like we did so far?

@streamer45 I would say we should rely on correct usage.

**Comment by agnivade** [comment]
On second thought, I have something to add to that. I actually encountered a similar thing in a PR earlier and completely forgot about that here.

The right way here is to add tests. Tests are a mechanism to lock in behavior so that they do not regress. Once we have a test for this behavior, we don't need additional error checking, nor do we need to rely on users to write the right code. Tests would just start to fail if they don't.

**Comment by streamer45** [comment]
> On second thought, I have something to add to that. I actually encountered a similar thing in a PR earlier and completely forgot about that here.
> 
> The right way here is to add tests. Tests are a mechanism to lock in behavior so that they do not regress. Once we have a test for this behavior, we don't need additional error checking, nor do we need to rely on users to write the right code. Tests would just start to fail if they don't.

Do you have something specific in mind? This was a odd kind of bug (reading the wrong variable), maybe a static checker could have helped spotting it.

**Comment by agnivade** [comment]
Nah nothing specific. Just theoretically speaking.

**Pull request merged**
