### PR TITLE
MM-51553: Update AMI to use latest LTS

### PR DESCRIPTION
**Pull request by agnivade**
I was getting issues while installing the linux-tools-* package.
Bumping up the AMI version to use the latest package. Also, the AMI
hasn't been updated in a while. So it's good to do it.

https://mattermost.atlassian.net/browse/MM-51553

### CODE REVIEW

**Review by streamer45 — APPROVED** [review]
It's been a while, I just hope this is not going to randomly break things.

**Comment by streamer45** [comment]
Yes, I was more worried about obscure failures like what we saw with a certain customer but agree this had to happen eventually.

**Review by agarciamontoro — APPROVED** [review]
Looks good! I'm wondering wheter we should batch the testing for this repo in a per-release test step, or do it per PR. In any case, we need testing here.

**Comment by agnivade** [comment]
I'd say we can do it in a case by case basis. For this one, yes I'd lean on testing the PR itself.

**Comment by DHaussermann** [comment]
@agarciamontoro I'm not sure the simplest way to test this.

I'm on Mac OS. I do have a linux piece of hardware available I can try and push up to the latest LTS and install this particular tool. Or perhaps there is some type of Docker solution for setup here?

Let me know if you have any thoughts.

**Comment by agnivade** [comment]
@DHaussermann - All you need to do here is do a deployment with this and smoke test the server. That should be it. It does not matter what hardware you have locally.

**Comment by agarciamontoro** [comment]
Yup, what @agnivade said. What this PR changed is the AMI used in the deployed instances, so it's just a matter of making a deployment and run a test. No need even to compare two tests, just make sure that running a test is successful and there's no regression.

**Comment by agnivade** [comment]
@DHaussermann - Did you get a chance to look into this?

**Comment by DHaussermann** [comment]
@agnivade I hit an unrelated tooling issue when I tried to test this where the code in the Terraform tooling was not able to record my IP address during the create process.
@agarciamontoro was helping me debug this but we could not solve it.

I will try this again on my Friday.

**Comment by agnivade** [comment]
Gave it a bit of smoke testing. Nothing major overall. One problem that I noticed was that the websocket connection kept getting disconnected. I am assuming it's to do with AWS and my ISP. Also, somehow the `getChannelMember` call always gave 404. But I ran another test with master and that also gave same results so it's nothing to do with this specific change. 

Some interesting logs:
```
{"timestamp":"2023-08-07 05:44:15.725 Z","level":"warn","msg":"failed to get public IP address for local interface","caller":"app/plugin_api.go:979","plugin_id":"com.mattermost.calls","origin":"main.(*logger).Warn log.go:99","localAddr":"127.0.0.1","error":"failed to get public address: write udp4 127.0.0.1:8443->52.72.139.62:3478: sendto: invalid argument"}
```

Don't think it has anything to do with this change, but just wanted to highlight. @streamer45

**Comment by streamer45** [comment]
> Gave it a bit of smoke testing. Nothing major overall. One problem that I noticed was that the websocket connection kept getting disconnected. I am assuming it's to do with AWS and my ISP. Also, somehow the `getChannelMember` call always gave 404. But I ran another test with master and that also gave same results so it's nothing to do with this specific change.

That's interesting. Regardless of this change, does it make sense to look into this? `getChannelMember` should not fail consistently I suppose.

> Some interesting logs:
>
> ```
> {"timestamp":"2023-08-07 05:44:15.725 Z","level":"warn","msg":"failed to get public IP address for local interface","caller":"app/plugin_api.go:979","plugin_id":"com.mattermost.calls","origin":"main.(*logger).Warn log.go:99","localAddr":"127.0.0.1","error":"failed to get public address: write udp4 127.0.0.1:8443->52.72.139.62:3478: sendto: invalid argument"}
> ```
> 
> Don't think it has anything to do with this change, but just wanted to highlight. @streamer45

I think that log is expected, although avoidable. In order to automatically figure out the public IP of the instance, we loop on all available interfaces and try to connect to the public STUN server. However, sending a udp message from the loopback device to a public IP is likely always going to fail. The following log line should be a successful one as eventually we should hit the interface actually routed to the public IP (172.x.x.x in our VPC).

**Comment by agnivade** [comment]
> That's interesting. Regardless of this change, does it make sense to look into this? getChannelMember should not fail consistently I suppose.

It's something to do with our gencontroller I think. Makes sense to investigate. I can open a ticket unless you were already planning to.

**Comment by streamer45** [comment]
> > That's interesting. Regardless of this change, does it make sense to look into this? getChannelMember should not fail consistently I suppose.
> 
> It's something to do with our gencontroller I think. Makes sense to investigate. I can open a ticket unless you were already planning to.

Not really, but agree, let's open a ticket and whoever finds the bandwidth can look in to it. Thanks!

**Comment by agnivade** [comment]
https://mattermost.atlassian.net/browse/MM-53940

**Pull request merged**
