### PR TITLE
MM-53845: Use external bucket

### PR DESCRIPTION
**Pull request by agnivade**
Add ability to use an external S3 bucket. This allows
us to restore a bucket before hand and just point to it.

https://mattermost.atlassian.net/browse/MM-53845

### CODE REVIEW

**Comment by agnivade** [comment]
cc @coltoneshaw - Now you can remove the forked commit.

**Comment by agnivade** [comment]
This also means we can get rid of the copy bucket logic and passing an external bucket URI. LMK if you want me to do this as part of this PR itself.

**Review by agarciamontoro — COMMENTED** [review]
Changes look good! But I have a dumb question: how easy is it to get all the info from the bucket manually? I mainly mean the `AccessKeyId` and the `SecretAccessKey`. Can we get those from our accounts in the load-test? Is there another way we can specify it?
I vaguely recall Colton and Stu had some problems getting that information (not sure if it was maybe a customer's specific issue), but I may be mistaken.

**Review by agarciamontoro — APPROVED** [review]

**Review by streamer45 — APPROVED** [review]
Nice improvement :+1:

**Pull request merged**
