### PR TITLE
MM-47265: Set default_text_search_config to english

### PR DESCRIPTION
**Pull request by agarciamontoro**
#### Summary
There are multiple places where we assume that the default language in the database is `english` (e.g., the GIN indexes are hardcoded to `english`), but the `default_text_search_config` parameter in Aurora defaults to `simple`. It is not possible to change that in the config level in AWS, so these changes make sure that the parameter has the expected value by altering the DB itself in two places:
- When creating any new Terraform deployment
- When running a comparison, which needs to reset the param after dropping and recreating the DB.

This has been tested with:
- `go run ./cmd/ltctl deployment create`
- `go run ./cmd/ltctl comparison run`

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-47265

### CODE REVIEW

**Review by isacikgoz — APPROVED** [review]
LGTM

**Comment by agnivade** [comment]
> It is not possible to change that in the config level in AWS, 

This was the PR for that: https://github.com/mattermost/mattermost-load-test-ng/pull/462

@streamer45 - I forget what was the reason we didn't merge it. Can we merge it now?

**Comment by streamer45** [comment]
> > It is not possible to change that in the config level in AWS,
> 
> This was the PR for that: #462
> 
> @streamer45 - I forget what was the reason we didn't merge it. Can we merge it now?

The reason is in https://github.com/mattermost/mattermost-load-test-ng/pull/462#issuecomment-1192808949

**Comment by agarciamontoro** [comment]
The thing is that `default_text_search_config` is not available in DB parameters group, so even if we merge Claudio's PR (which we should at some point, it's just that other stuff has had more priority), we'll need the changes from this one too.
image

**Comment by agnivade** [comment]
Oh never mind then

**Review by agnivade — APPROVED** [review]

**Pull request merged**
