### PR TITLE
MM-21959: Use a middleware to pass the load test

### PR DESCRIPTION
**Pull request by agnivade**
#### Ticket Link

https://mattermost.atlassian.net/browse/MM-21959

### CODE REVIEW

**Comment by agnivade** [comment]
Code cleanliness-wise yes it's the same. But I think conceptually it makes things simpler.

Previously, each handler called the same function every time. Now it's just being called once. So the handlers themselves don't need to bother about how to get the loadAgentId. They can just access it from the context and get about doing their stuff. The middleware now does that job.

That was my thinking. Let me know what you think.

**Comment by reflog** [comment]
Well, the function isn't "called once", it's called by the middleware for each request - so we just shifted the responsibility to middleware.
In general - I agree with your approach, but it seems it doesn't add anything in this case. I'm ok with merging this, nothing bad here, I just think it's a bit redundant

**Comment by agnivade** [comment]
Fair enough. I'm okay with closing this if you prefer. LMK.

**Comment by reflog** [comment]
I think we can close this. Seems to add more code with little benefit.

**Pull request closed without merging**
