### PR TITLE
MM-21676: Fix panic on closed channel

### PR DESCRIPTION
**Pull request by agnivade**
#### Summary

Re-initialize the status channel when starting a run.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-21676

### CODE REVIEW

**Comment by agnivade** [comment]
I had already tried to add that. :) Currently, it's not possible to do that without spinning up an active server, because without that, the status channel don't get populated.

**Comment by streamer45** [comment]
> I had already tried to add that. :) Currently, it's not possible to do that without spinning up an active server, because without that, the status channel don't get populated.

Aren't we already doing that in `TestRun`?
Just hacking that test (adding a Run() call) made the panic happen for me.

**Comment by agnivade** [comment]
It's not working for me. I can do that if you prefer.

**Comment by streamer45** [comment]
> It's not working for me. I can do that if you prefer.

Interesting.

```patch
diff --git a/loadtest/loadtest_test.go b/loadtest/loadtest_test.go
index bd46208..79eed15 100644
--- a/loadtest/loadtest_test.go
+++ b/loadtest/loadtest_test.go
@@ -103,6 +103,12 @@ func TestRun(t *testing.T) {
 
        err = lt.Stop()
        require.NoError(t, err)
+
+       err = lt.Run()
+       require.NoError(t, err)
+
+       err = lt.Stop()
+       require.NoError(t, err)
 }
 
 func TestStop(t *testing.T) {
```

This before this PR would panic for me, after it won't.

**Comment by agnivade** [comment]
Oh I'm dumb. :man_facepalming: nvm.

**Pull request merged**
