### PR TITLE
Use new frequencies based on cloud customer

### PR DESCRIPTION
**Pull request by agarciamontoro**
#### Summary
These are the initial frequencies computed using the [Grafana](https://docs.google.com/spreadsheets/d/1l6cHa1vW3dCFI3-LqqFdiJTmYQD0FadoI3oPHkKPIZA/edit#gid=604980166), [DB](https://docs.google.com/spreadsheets/d/1l6cHa1vW3dCFI3-LqqFdiJTmYQD0FadoI3oPHkKPIZA/edit#gid=759740678) and [telemetry](https://docs.google.com/spreadsheets/d/1l6cHa1vW3dCFI3-LqqFdiJTmYQD0FadoI3oPHkKPIZA/edit#gid=539193463) data from the cloud customer.

#### Ticket Link
--

### CODE REVIEW

**Review by streamer45 — APPROVED** [review]
Nicely done :snowflake:

**Review by agnivade — APPROVED** [review]
So basically it looks like all people do is switch channels all day.

**Comment by agarciamontoro** [comment]
> So basically it looks like all people do is switch channels all day.

This was actually the same in Community!

**Comment by agarciamontoro** [comment]
Although we do need to reduce that a bit (due to the `viewChannel` handler being used elsewhere as well), but that'll be another PR.

**Pull request merged**
