### PR TITLE
MM-46639: Insights actions - updated

### PR DESCRIPTION
**Pull request by plant99**
#### Summary

1. Adds insights call actions for top DMs, top inactive channels, and new team members.
2. Change limit parameter to insights calls.
#### Ticket Link

https://mattermost.atlassian.net/browse/MM-46639

### CODE REVIEW

**Comment by agnivade** [comment]
Great stuff Shivashish! Can we run a bounded load test with the new coverage and compare that without this PR?

**Comment by agarciamontoro** [comment]
I'll be off next week, back on Tuesday September 6, so I won't be able to review until then. Sorry for that :pray:

**Comment by plant99** [comment]
@agnivade http://3.83.65.36:3000/?orgId=1&refresh=10s&var-server=agent-0:4000&var-server=app-0:8067&var-server=app-0:9100&var-server=agent-1:4000&from=now-24h&to=now this is the loadtest result.

please consider loadtest 1, 3. The second loadtest is faulty.

**Review by mkraft — APPROVED** [review]

**Comment by agnivade** [comment]
I can see some regressions in p99 times for `histogram_quantile(0.99, sum(rate(mattermost_db_store_time_bucket{method=~".*GetTop.*"}[1m])) by (instance, method,le))`. I think it's worth perhaps a second run with the new code to see if the same pattern continues.

new
old

**Review by agnivade — APPROVED** [review]
Nice work!

**Review by mkraft — APPROVED** [review]

**Pull request merged**
