### PR TITLE
MM-47876: Remove deprecated acl attribute

### PR DESCRIPTION
**Pull request by agarciamontoro**
#### Summary
Just a small improvement to remove an annoying deprecation warning. The important changes are the ones from the first commit. The second is simply the result of running `make assets`.

I'm testing this right now with the creation of a deployment, but you can already review.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-47876

### CODE REVIEW

**Review by agnivade — APPROVED** [review]

**Comment by agarciamontoro** [comment]
My `go fmt` is behaving differently than the one in CI. Probably because I have Go 1.19 locally and CI has 1.18 :thinking:

**Comment by agarciamontoro** [comment]
The test was successful. Now I only have to understand what the `go fmt` is doing with the spacing in CI :unamused:

**Comment by noxer** [comment]
The `bindata.go` file is not properly formatted, no matter which version.

**Comment by agarciamontoro** [comment]
> The bindata.go file is not properly formatted, no matter which version.

Yes, and I don't understand why. The formatting in CI differs with my local formatting, even with the same version of Go and go-bindata.

**Comment by agarciamontoro** [comment]
It's green now :shrug: It seems it was one of those formattings that's accepted in several forms.

**Comment by agarciamontoro** [comment]
Friendly ping, @noxer.

**Review by noxer — APPROVED** [review]
Sorry, I missed you fixing it. Looks good. Thanks.

**Pull request merged**
