### PR TITLE
[MM-34266] Various upgrades and tunings

### PR DESCRIPTION
**Pull request by streamer45**
#### Summary

PR addresses some of the actions that came out of the recent 25K performance analysis:

- Upgrade instances AMIs.
- Added some tooling (e.g. `perf`).
- Provide the tunings and config changes that most helped scaling.
- Provided a way (through env variables) to dynamically set advanced deployment options (e.g. setting TCP_NO_DELAY).

#### Most noticeable results

image

image

#### Consulted resources

- https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking-ena.html
- https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking-os.html
- https://linuxczar.net/blog/2016/09/18/bandwidth-delay-product/
- https://www.extrahop.com/company/blog/2016/tcp-nodelay-nagle-quickack-best-practices/
- https://dropbox.tech/infrastructure/optimizing-web-servers-for-high-throughput-and-low-latency (a real gold mine but rabbit hole as the same time)
- https://cromwell-intl.com/open-source/performance-tuning/tcp.html
- https://blog.cloudflare.com/http-2-prioritization-with-nginx/
- https://blog.cloudflare.com/syn-packet-handling-in-the-wild/
- https://blog.cloudflare.com/the-story-of-one-latency-spike/
- https://blog.cloudflare.com/path-mtu-discovery-in-practice/
- https://bl.ocks.org/magnetikonline/2760f98f6bf654d5ad79

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-34266

### CODE REVIEW

**Review by agnivade — APPROVED** [review]
This is brilliant research!

Now where is that blog post? ;) I would love to read a detailed analysis of the entire process!

**Comment by agnivade** [comment]
Also fixes https://mattermost.atlassian.net/browse/MM-33229

**Comment by streamer45** [comment]
> This is brilliant research!
>
> Now where is that blog post? ;) I would love to read a detailed analysis of the entire process!

:beers:  I am a real slug when it comes to writing content but I'll add it to the queue :stuck_out_tongue: 

> Also fixes https://mattermost.atlassian.net/browse/MM-33229

Thanks, I have been looking for that.

**Review by isacikgoz — APPROVED** [review]
This is great, it must required a lot of focus to figure out these adjustments! 🎉

**Pull request merged**
