### PR TITLE
[MM-23528] Add documentation for coordinator's config

### PR DESCRIPTION
**Pull request by streamer45**
#### Summary

PR adds documentation for coordinator's config.
Still a work in progress but ready for initial review and thoughts.

#### Ticket

https://mattermost.atlassian.net/browse/MM-23528

### CODE REVIEW

**Comment by agnivade** [comment]
Looks good. We should also add the loadtest config.

**Comment by streamer45** [comment]
> Looks good. We should also add the loadtest config.

We have a [ticket](https://mattermost.atlassian.net/browse/MM-23527) for that or you mean to add it here somehow?

**Comment by agnivade** [comment]
I see. I meant we should mention that load test config is contained in the coordinator config. We can just link to that .md file from here.

**Comment by isacikgoz** [comment]
Looks good, it might be *inconvenient* but maybe we can add value ranges, thoughts?

**Comment by streamer45** [comment]
> Looks good, it might be _inconvenient_ but maybe we can add value ranges, thoughts?

Like `(0, +∞)` for `MaxActiveUsers` ? :grinning:

**Pull request merged**
