### PR TITLE
Bump DB engine versions

### PR DESCRIPTION
**Pull request by agnivade**

### CODE REVIEW

**Comment by agnivade** [comment]
Sure. I haven't run a test myself, so would be good to verify. Sometimes, the version strings are weird.

**Comment by streamer45** [comment]
So, the good news is it worked without issues:

```
==================================================
Comparison result:
Report: report_0.md
Grafana Dashboard: http://52.207.24.209:3000/d/2M5zgJTMz/comparison-0-mysql-unbounded
v5.28.1:
  Type: unbounded
  DB Engine: mysql
  Supported Users: 2973
  Errors: 9293
v5.29.0-rc2:
  Type: unbounded
  DB Engine: mysql
  Supported Users: 2968
  Errors: 5806
==================================================

==================================================
Comparison result:
Report: report_1.md
Grafana Dashboard: http://52.87.208.131:3000/d/aOpigJoMz/comparison-0-postgresql-unbounded
v5.28.1:
  Type: unbounded
  DB Engine: postgresql
  Supported Users: 2277
  Errors: 8951
v5.29.0-rc2:
  Type: unbounded
  DB Engine: postgresql
  Supported Users: 2404
  Errors: 5191
==================================================
```

Now the *bad* news is that we dropped more than 600 users on postgres.
Recent unbounded comparison was showing ~3000 users.

This clearly needs further investigation.

**Comment by agnivade** [comment]
Sounds good. But it still looks like a net improvement no? Your last post on the performance channel showed similar performance AFAIR .. right?

**Comment by streamer45** [comment]
> Sounds good. But it still looks like a net improvement no? Your last post on the performance channel showed similar performance AFAIR .. right?

Not really. These were the most recent results for unbounded postgres, on pretty much the same builds:

```
==================================================
Comparison result:
Report: report_1.md
Grafana Dashboard: http://34.207.153.238:3000/d/Fb0Y99hGz/comparison-0-postgresql-unbounded
v5.28.1:
  Type: unbounded
  DB Engine: postgresql
  Supported Users: 3024
v5.29.0-rc2:
  Type: unbounded
  DB Engine: postgresql
  Supported Users: 3038
==================================================
```

**Comment by agnivade** [comment]
I see. I do hope it's not the Aurora unreliability again.

If another test on a fresh cluster shows similar results, we definitely need to look into this.

OTOH, it's great to see such information being available with just one command. :) We should start documenting and capturing them somewhere.

**Comment by streamer45** [comment]
> I see. I do hope it's not the Aurora unreliability again.
> 
> If another test on a fresh cluster shows similar results, we definitely need to look into this.

Yes, adding as a next step.

> OTOH, it's great to see such information being available with just one command. :) We should start documenting and capturing them somewhere.

https://mattermost.atlassian.net/browse/MM-29243 :stuck_out_tongue:

**Comment by streamer45** [comment]
So, took a good look at this:

I was able to reproduce the same issue again yesterday on a multi app cluster setup (2 app servers and 2 db, 1 reader 1 writer). The interesting part was that both API and Store times and any other metric showed no differences except for client request times. That led me to think it could have been an issue with the agents. I then switched the DBs in the two deployments to verify this and didn't get the same issue.

Today I thought of trying a simpler setup, 1 App server, 1 db writer and results were definitely closer, although there was a noticeable rise in Store Times (between 20 and 40%). I ran two bounded load-tests at 1000 and 1500 users.
After those I added a read replica to both deployments and tested again at 1500. Finally I ran an unbounded load-test. 

### Bounded load-test 1000 users (1 db writer)

Left side is 9.6.8, right is 11.7

image

### Bounded load-test 1500 users (1 db writer)

Left side is 9.6.8, right is 11.7

image

### Bounded load-test 1500 users (1 db writer, 1 reader)

Left side is 9.6.8, right is 11.7

image

### Unbounded load-test

#### aurora-postgresql 9.6.8

```
==================================================
load-test status:

State: done
Start time: Fri Nov 20 14:46:07 UTC 2020
Stop time: Fri Nov 20 15:36:01 UTC 2020
Duration: 49m54s
Active users: 0
Connected users: 0
Number of errors: 11373
  - Timeouts: 9185 (80.76%)
  - HTTP 5xx: 0 (0.00%)
  - HTTP 4xx: 2188 (19.24%)
Supported users: 2099
==================================================
```

#### aurora-postgresql 11.7

```
==================================================
load-test status:

State: done
Start time: Fri Nov 20 14:46:05 UTC 2020
Stop time: Fri Nov 20 15:28:38 UTC 2020
Duration: 42m34s
Active users: 0
Number of errors: 10796
  - Timeouts: 8636 (79.99%)
  - HTTP 5xx: 0 (0.00%)
  - HTTP 4xx: 2160 (20.01%)
Supported users: 2090
==================================================
```

Full data is at http://52.90.228.63:3000/

To be extremely thorough, a next step would be to run a test on a bigger data set (1M posts).
Also a third attempt on a multi app cluster would be nice to completely exclude any funny side effect.

**Comment by agnivade** [comment]
Yeah, I do see around 20% delay in the call times. We'll probably need to take top 10 slowest store calls from both setups and compare them. And if it's the same queries, then look into why there's a regression.

**Comment by streamer45** [comment]
It doesn't look like it's a specific method, although `PostStore` seems to be particularly affected.
This are results for the 1500 bounded test (1 db writer), sorted by delta.

### Store times avg (worsened):
| | | Base | Actual | Delta | Delta % |
| --- | --- | --- | --- | --- | --- |
| PostStore.SearchPostsInTeamForUser | avg | 11ms | 21ms | 10ms | 94.99
| PreferenceStore.Save | avg | 15ms | 24ms | 9ms | 58.51
| ChannelStore.CreateDirectChannel | avg | 22ms | 31ms | 9ms | 41.23
| PostStore.Update | avg | 29ms | 37ms | 8ms | 27.63
| ChannelStore.SaveMember | avg | 15ms | 23ms | 8ms | 53.86
| ProductNoticesStore.ClearOldNotices | avg | 4ms | 12ms | 8ms | 207.58
| ChannelStore.AutocompleteInTeamForSearch | avg | 22ms | 30ms | 8ms | 36.06
| PostStore.AnalyticsPostCountsByDay | avg | 1ms | 9ms | 8ms | 611.43
| PostStore.Save | avg | 30ms | 37ms | 7ms | 23.01
| JobStore.UpdateStatusOptimistically | avg | 4ms | 9ms | 5ms | 113.51
| ReactionStore.Save | avg | 14ms | 19ms | 5ms | 36.54
| ChannelStore.UpdateLastViewedAt | avg | 14ms | 19ms | 5ms | 34.53
| SessionStore.GetSessionsExpired | avg | 3ms | 8ms | 5ms | 187.29
| PreferenceStore.Get | avg | 3ms | 8ms | 5ms | 144.77
| JobStore.GetAllByStatus | avg | 5ms | 9ms | 4ms | 75.54
| JobStore.UpdateStatus | avg | 5ms | 9ms | 4ms | 88.67
| ChannelStore.IncrementMentionCount | avg | 20ms | 24ms | 4ms | 19.83
| SessionStore.Save | avg | 12ms | 16ms | 4ms | 34.53
| PostStore.GetPostsBefore | avg | 14ms | 18ms | 4ms | 28.96
| PostStore.GetPostsAfter | avg | 14ms | 17ms | 3ms | 21.92
| FileInfoStore.Save | avg | 14ms | 17ms | 3ms | 20.89
| ChannelStore.Save | avg | 14ms | 17ms | 3ms | 21.71
| StatusStore.SaveOrUpdate | avg | 12ms | 15ms | 3ms | 25.04
| ChannelStore.GetByName | avg | 3ms | 5ms | 2ms | 58.30
| ChannelStore.UpdateSidebarChannelsByPreferences | avg | 2ms | 4ms | 2ms | 114.37
| ChannelMemberHistoryStore.LogJoinEvent | avg | 5ms | 7ms | 2ms | 36.93
| SessionStore.UpdateLastActivityAt | avg | 7ms | 9ms | 2ms | 28.82
| SessionStore.GetSessionsWithActiveDeviceIds | avg | 3ms | 5ms | 2ms | 61.61
| CommandStore.AnalyticsCommandCount | avg | 1ms | 3ms | 2ms | 228.40
| ChannelStore.SearchGroupChannels | avg | 10ms | 12ms | 2ms | 20.41
| UserStore.GetByUsername | avg | 4ms | 6ms | 2ms | 54.15
| PostStore.GetPosts | avg | 6ms | 8ms | 2ms | 33.72
| UserStore.GetUnreadCount | avg | 4ms | 6ms | 2ms | 46.65
| GroupStore.AdminRoleGroupsForSyncableMember | avg | 3ms | 5ms | 2ms | 64.89
| StatusStore.UpdateLastActivityAt | avg | 6ms | 8ms | 2ms | 35.25
| FileInfoStore.AttachToPost | avg | 9ms | 11ms | 2ms | 22.66
| PluginStore.Delete | avg | 4ms | 6ms | 2ms | 54.70
| TeamStore.Get | avg | 3ms | 5ms | 2ms | 61.40
| UserTermsOfServiceStore.GetByUser | avg | 2ms | 4ms | 2ms | 81.95
| ChannelStore.GetChannels | avg | 6ms | 8ms | 2ms | 32.56
| ThreadStore.CreateMembershipIfNeeded | avg | 9ms | 11ms | 2ms | 22.32
| ChannelStore.SearchInTeam | avg | 7ms | 9ms | 2ms | 27.11
| ChannelStore.GetMember | avg | 6ms | 8ms | 2ms | 31.77
| PluginStore.SetWithOptions | avg | 10ms | 12ms | 2ms | 20.95
| TeamStore.GetByName | avg | 3ms | 5ms | 2ms | 73.35
| StatusStore.GetByIds | avg | 4ms | 6ms | 2ms | 45.58
| PostStore.Get | avg | 14ms | 16ms | 2ms | 14.33
| PostStore.GetPostIdAfterTime | avg | 3ms | 5ms | 2ms | 67.79
| UserStore.GetUnreadCountForChannel | avg | 3ms | 5ms | 2ms | 59.84
| ChannelStore.GetMembersForUser | avg | 7ms | 9ms | 2ms | 28.45
### Store times p99 (worsened):
| | | Base | Actual | Delta | Delta % |
| --- | --- | --- | --- | --- | --- |
| PostStore.SearchPostsInTeamForUser | p99 | 88ms | 158ms | 70ms | 79.85
| ChannelStore.CreateDirectChannel | p99 | 125ms | 193ms | 68ms | 54.47
| PreferenceStore.Save | p99 | 103ms | 159ms | 56ms | 54.12
| UserStore.GetAllProfilesInChannel | p99 | 278ms | 332ms | 54ms | 19.39
| SessionStore.Save | p99 | 87ms | 132ms | 45ms | 51.99
| PreferenceStore.Get | p99 | 33ms | 68ms | 35ms | 105.07
| ChannelStore.SaveMember | p99 | 92ms | 120ms | 28ms | 30.29
| JobStore.GetAllByStatus | p99 | 63ms | 89ms | 26ms | 41.49
| ChannelStore.AutocompleteInTeamForSearch | p99 | 190ms | 215ms | 25ms | 13.14
| ChannelStore.GetMembersForUser | p99 | 51ms | 74ms | 23ms | 44.78
| SessionStore.GetSessionsExpired | p99 | 5ms | 25ms | 20ms | 404.04
| ProductNoticesStore.ClearOldNotices | p99 | 5ms | 25ms | 20ms | 404.04
| SessionStore.GetSessionsWithActiveDeviceIds | p99 | 28ms | 44ms | 16ms | 56.77
| JobStore.UpdateStatus | p99 | 10ms | 24ms | 14ms | 141.56
| PluginStore.Delete | p99 | 33ms | 45ms | 12ms | 36.21
| PostStore.Update | p99 | 204ms | 216ms | 12ms | 5.87
| ChannelStore.GetPublicChannelsForTeam | p99 | 64ms | 75ms | 11ms | 17.07
| UserStore.GetByUsername | p99 | 29ms | 40ms | 11ms | 37.93
| PostStore.GetPostIdBeforeTime | p99 | 24ms | 34ms | 10ms | 41.56
| ChannelStore.UpdateLastViewedAt | p99 | 98ms | 107ms | 9ms | 9.22
| UserStore.GetUnreadCount | p99 | 43ms | 51ms | 8ms | 18.63
| ReactionStore.Save | p99 | 96ms | 104ms | 8ms | 8.38
| ClusterDiscoveryStore.GetAll | p99 | 90ms | 98ms | 8ms | 8.91
| PostStore.GetPostIdAfterTime | p99 | 31ms | 38ms | 7ms | 22.73
| ChannelStore.SearchInTeam | p99 | 78ms | 85ms | 7ms | 8.93
| ChannelStore.UpdateSidebarChannelsByPreferences | p99 | 20ms | 27ms | 7ms | 34.92
| ChannelStore.SearchGroupChannels | p99 | 85ms | 90ms | 5ms | 5.87
| PostStore.AnalyticsPostCountsByDay | p99 | 5ms | 10ms | 5ms | 101.01
| PostStore.GetPostsBefore | p99 | 94ms | 99ms | 5ms | 5.33
| TeamStore.Get | p99 | 36ms | 41ms | 5ms | 13.92
| UserStore.GetUnreadCountForChannel | p99 | 35ms | 40ms | 5ms | 14.22
| ChannelStore.Get | p99 | 10ms | 14ms | 4ms | 41.17
| PluginStore.SetWithOptions | p99 | 72ms | 76ms | 4ms | 5.57
| PostStore.GetPosts | p99 | 45ms | 49ms | 4ms | 8.92
| FileInfoStore.Get | p99 | 30ms | 34ms | 4ms | 13.40
| PostStore.GetPostsAfter | p99 | 96ms | 100ms | 4ms | 4.18
| TeamStore.GetByName | p99 | 21ms | 25ms | 4ms | 19.46
| SessionStore.UpdateLastActivityAt | p99 | 46ms | 50ms | 4ms | 8.66
| UserStore.GetProfilesByUsernames | p99 | 63ms | 67ms | 4ms | 6.38
| ChannelStore.GetPinnedPostCount | p99 | 16ms | 19ms | 3ms | 19.15
| PostStore.Save | p99 | 226ms | 229ms | 3ms | 1.32
| UserTermsOfServiceStore.GetByUser | p99 | 23ms | 26ms | 3ms | 12.78
| JobStore.UpdateStatusOptimistically | p99 | 23ms | 25ms | 2ms | 8.57
| ChannelStore.GetMember | p99 | 57ms | 59ms | 2ms | 3.52
| ChannelStore.GetMemberCount | p99 | 13ms | 15ms | 2ms | 15.94
| AuditStore.Save | p99 | 48ms | 50ms | 2ms | 4.13
| GroupStore.GetGroups | p99 | 21ms | 23ms | 2ms | 9.59
| ChannelMemberHistoryStore.LogJoinEvent | p99 | 45ms | 47ms | 2ms | 4.44
| ChannelStore.GetAllChannelMembersForUser | p99 | 22ms | 24ms | 2ms | 8.95

**Comment by agnivade** [comment]
Hmm .. this is a bit concerning. I'm wondering if there is some config tuning part that we are missing, due to which stock pg 11 performs poorly than stock pg 9.6.

Just to be sure, can we take a look at the store handler level Grafana graphs? Just to be sure that the lag is consistent across time and not polluted by any sudden spikes.

Assuming that the degradation is throughout, we probably need to discuss this a bit more.

**Comment by streamer45** [comment]
> Hmm .. this is a bit concerning. I'm wondering if there is some config tuning part that we are missing, due to which stock pg 11 performs poorly than stock pg 9.6.
> 
> Just to be sure, can we take a look at the store handler level Grafana graphs? Just to be sure that the lag is consistent across time and not polluted by any sudden spikes.
> 
> Assuming that the degradation is throughout, we probably need to discuss this a bit more.

Agreed. I've prepared a simple dashboard to quickly jump from method to method and see the comparison:

http://52.90.228.63:3000/d/RCdSRjoMz/store-times-comparison?orgId=1

**Comment by agnivade** [comment]
Hmm ... this seems uniformly bad. I did manage to find one query that improved http://52.90.228.63:3000/d/RCdSRjoMz/store-times-comparison?orgId=1&var-method=UserStore.Search :P But that just might be a fluke.

So are the next steps
- do another test with 11.8
- do a test with a large dataset
?

**Comment by streamer45** [comment]
> Hmm ... this seems uniformly bad. I did manage to find one query that improved http://52.90.228.63:3000/d/RCdSRjoMz/store-times-comparison?orgId=1&var-method=UserStore.Search :P But that just might be a fluke.

Yes, it seems that there was a worsening overall.

> So are the next steps
> 
> * do another test with 11.8
> * do a test with a large dataset
>   ?

Yes, that would be my plan.
There would also be the "aurora config tweaks" route to explore but I know that can rapidly become a rabbit hole so for now I am thinking of sticking with defaults.

**Comment by streamer45** [comment]
Just ran a bounded load-test on a 2.6M posts dataset on all three version (9.6.8, 11.7, 11.8). Results are more or less the same. 9.6.8 consistently showing quicker times on both set and get store operations.

image

image

image

[Store Times Dashboard](http://54.224.68.183:3000/d/RCdSRjoMz/store-times-comparison?orgId=1&from=1606298576723&to=1606300748971&var-method=PostStore.Get)
[Main Dashboard](http://54.224.68.183:3000/d/000000011/mattermost-load-test-performance-monitoring?orgId=1&from=1606296851387&to=1606300848806&var-server=app-0:8067)

**Comment by agnivade** [comment]
Okay, so the results are pretty much consistent. It looks like we have to jump in the rabbit hole. :(

**Review by streamer45 — APPROVED** [review]

**Pull request merged**
