### PR TITLE
[MM-20869] Adds check-style make target and fixes lint errors

### PR DESCRIPTION
**Pull request by mgdelacroix**

### CODE REVIEW

**Comment by agnivade** [comment]
Maybe an ignorant question, but I don't see the circleCI pipeline being run here. Isn't this something which needs to happen ?

**Comment by mgdelacroix** [comment]
I was planning on raising the same question as I saw that we already have a `.circleci` set up and some previous work existed. Now on a second read I think the file was copied over rather than specifically set up for the project, so I'm happy to add a basic lint&test workflow to this PR. @streamer45 can you please confirm this is the right approach?

**Comment by agnivade** [comment]
Oh, then we just need to add this repo to circleCI. Otherwise it won't pick it up. pinging @cpanato.

**Comment by streamer45** [comment]
Yes, that was in the backlog of things to do for sure. I don't know if the current file will work without modifications. If not, feel free to open a PR.

**Comment by cpanato** [comment]
enabled:
- [x] mattermod
- [x] circleci

**Comment by mgdelacroix** [comment]
Thanks @cpanato!!! :smile:

**Comment by cpanato** [comment]
master is broken as well, fyi

**Comment by streamer45** [comment]
> master is broken as well, fyi

Yes we are aware, we need to make a PR to fix the circleci config since it's coming for a forked repository and it needs some touches.

**Comment by mgdelacroix** [comment]
I'll merge this one and will create another one with the CI changes

**Pull request merged**
