### PR TITLE
[MM-23895] Specify required Terraform version

### PR DESCRIPTION
**Pull request by streamer45**
#### Summary

PR adds version requirement for Terraform in documentation.

#### Ticket

https://mattermost.atlassian.net/browse/MM-23895

### CODE REVIEW

**Comment by streamer45** [comment]
> Oh I thought we were going to add a check from the code to verify the version ? We just need to add that in `preFlightCheck`.

We can surely do both but this is about documentation and preventing the user from getting an error by being explicit on the requirements. The code check will be needed if the user didn't read/follow the documentation. It's like a second layer of *security* from misusage.

**Comment by agnivade** [comment]
Yeah, we can do it in a separate PR for sure. But it is good to make the tool more robust.

I am thinking of it as our config validation code. We do document the options which are allowed for the DB like - aurora-mysql and aurora-postgresql. But we validate them anyways to prevent the deployment from failing.

**Comment by streamer45** [comment]
> Yeah, we can do it in a separate PR for sure. But it is good to make the tool more robust.
> 
> I am thinking of it as our config validation code. We do document the options which are allowed for the DB like - aurora-mysql and aurora-postgresql. But we validate them anyways to prevent the deployment from failing.

Yes, :+1: for me.

**Comment by streamer45** [comment]
@agnivade 

Created https://mattermost.atlassian.net/browse/MM-23916 for the additional in-code check.

**Pull request merged**
